# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20171026_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.CharField(blank=True, choices=[('page', 'Page'), ('blog', 'Blog'), ('post', 'Post'), ('story', 'Story'), ('chapter', 'Chapter')], max_length=1),
        ),
    ]
