# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('page', 'Page'), ('blog', 'Blog'), ('post', 'Post'), ('story', 'Story'), ('chapter', 'Chapter')], max_length=100),
        ),
    ]
